In [1]:
import numpy as np

In [3]:
arr = np.array([[1, 2, 3],[2, 3, 4],[3, 4, 5]])

In [4]:
print(arr)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [5]:
arr_transpose = arr.transpose()

In [6]:
print(arr_transpose)

[[1 2 3]
 [2 3 4]
 [3 4 5]]
